name: Release

on:
  push:
    tags:
      - "[0-9]+"

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: BigWigsMods/packager@v2
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
